stages:
    - build


build:
    stage: build
    cache:
        paths: 
            - dist-newstyle
    tags:
        - shell
    script:
        - docker info
        - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - if [ "$CI_COMMIT_REF_NAME" == "develop" ]; then COMMON_TAG="nightly"; elif [ "$CI_COMMIT_REF_NAME" == "master" ]; then COMMON_TAG="latest"; else COMMON_TAG=$CI_COMMIT_REF_SLUG; fi
        - ./.ci/build cabal update
        - ./.ci/build  -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$COMMON_TAG
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:$COMMON_TAG

